global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s
remote_write:
- basic_auth:
    password: xxxx
    username: yyyy
  name: staging-aiops
  url: zzzz
scrape_configs:
- follow_redirects: true
  honor_timestamps: true
  job_name: user_metrics
  metrics_path: /metrics
  scheme: http
  scrape_interval: 10s
  scrape_timeout: 5s
  static_configs:
  - targets:
    - localhost:8123
